### ISSUE TITLE
IE11 support for "new URL()" is gone...

### ISSUE THREAD

**Issue by Ado77** [PolymerElements/iron-location#74]
### Description

It looks like support for new URL() is gone from IE11

https://developer.mozilla.org/en/docs/Web/API/URL#Browser_compatibility

### Expected outcome
Navigation from anchor tags to not reload the entire page.

### Actual outcome
Navigation is causing the entire page to reload.

### Steps to reproduce
polymer init a PSK 2.0 and run it in ie 11
click navigation links on the left

### Dev Note :)
It's in the _getSameOriginLinkHref function.

### Browsers Affected

- [X] IE 11
- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 10

**Comment by Ado77** [comment]
@e111077 Not sure if you are the right person for this but seems like a big problem if you want to do routing...

**Comment by e111077** [comment]
Heya, I am the right person. We have received many complaints and have ran into huge issues when including our own polyfills in elements which is why the url polyfill was moved to the dev dependencies. Going on from 2.0 to further we are allowing developers to choose and use their own polyfills. If you want to use the same polyfill that we do:

`bower install -S webcomponents/URL#^0.5.7`

and then before you import `app-route` or `iron-location` you should include the polyfill. [Here ](https://github.com/PolymerElements/iron-location/blob/2.0-preview/test/integration.html#L28)is an example on how we do this in the tests.

**Comment by e111077** [comment]
I recommend leaving an issue to include the polyfill on the [PSK2 repo](https://github.com/PolymerElements/polymer-starter-kit)

**Comment by Ado77** [comment]
Ok, thanks for the quick reply :+1: . Maybe put it on the README of this repo? I suspect it will trip up a lot of people... I couldn't find any information on this...

**Comment by e111077** [comment]
That is a really good point. We've been putting breaking changes on the PRs. I've updated the PR for now.
